Repository SinergiaTIC/SinergiaCRM, pull requests merged in 2024-07, with the labels that each got.

#292 Hotfix - Vistas Personalizadas - Aplicación de las Personalizaciones durante la edición inline en Vista Detalle
  modules/stic_Custom_Views/processor/js/sticCVUtils.js
  modules/stic_Custom_Views/processor/js/sticCV_Record_Field_Content.js
Labels: bug, not urgent, Vistas personalizadas

#281 Hotfix - Registro horario - Error JS en página de Login
  custom/modules/Calendar/Calendar.php
  custom/themes/SuiteP/modules/Calendar/tpls/settings.tpl
  custom/themes/SuiteP/tpls/_head.tpl
  custom/themes/SuiteP/tpls/_headerModuleList.tpl
Labels: bug, not urgent, Registro horario

#301 Hotfix - Calendario laboral - Calcular correctamente el campo Día de la semana
  modules/stic_Work_Calendar/stic_Work_Calendar.php
Labels: bug, not urgent, Calendario laboral

#294 Hotfix - Acciones de validación - Error al comprobar las fechas para enviar el email a los administradores
  modules/stic_Validation_Actions/DataAnalyzer/DataAnalyzer.php
Labels: bug, not urgent, Validación de datos

#285 Hotfix - Vistas Personalizadas - No aplica personalizaciones en vista de creación rápida mostrada en PopUp
  modules/stic_Custom_Views/processor/LogicHooksCode.php
Labels: bug, not urgent, Vistas personalizadas

#287 Hotfix - Vistas Personalizadas - Visibilidad correcta en campos de pestaña/panel al ocultar y mostrar contenedor en vista de Edición y creación rápida
  modules/stic_Custom_Views/processor/js/sticCVUtils.js
  modules/stic_Custom_Views/processor/js/sticCV_Element_Div.js
  modules/stic_Custom_Views/processor/js/sticCV_Element_FieldContainer.js
  modules/stic_Custom_Views/processor/js/sticCV_Record_Container.js
  modules/stic_Custom_Views/processor/js/sticCV_Record_Field.js
  modules/stic_Custom_Views/processor/js/sticCV_Record_Field_Content.js
Labels: bug, urgent, Vistas personalizadas

#290 Hotfix - Vistas Personalizadas - Visualización correcta de campos requeridos
  modules/stic_Custom_Views/processor/js/sticCVUtils.js
Labels: bug, not urgent, Vistas personalizadas

#304 Hotfix - Sesiones - Campos mal informados en sesiones periódicas de un evento
  modules/stic_Events/Utils.php
  modules/stic_Events/language/ca_ES.lang.php
  modules/stic_Events/language/en_us.lang.php
  modules/stic_Events/language/es_ES.lang.php
  modules/stic_Events/language/gl_ES.lang.php
  modules/stic_Events/tpls/SessionWizard.tpl
Labels: bug, General, Sesiones y asistencias

#291 Hotfix - Vistas Personalizadas - Error al aplicar acciones en ciertas instancias
  modules/stic_Custom_Views/processor/js/sticCVUtils.js
Labels: bug, urgent, Vistas personalizadas

#296 Hotfix - Incripciones - Resetear campos calculados despues de duplicar masivamente inscripciones
  modules/stic_Registrations/LogicHooksCode.php
Labels: bug, Eventos e inscripciones

#305 Hotfix - Vistas Personalizadas - Usar hora correcta al comprobar las condiciones de las personalizaciones
  modules/stic_Custom_Views/processor/LogicHooksCode.php
Labels: bug, urgent, Vistas personalizadas

#15 Hotfix - General - Mostrar valor incorrecto en campos Enum y Multienum en vistas de lista, de detalle y popup
  include/SugarFields/Fields/Enum/DetailView.tpl
  include/SugarFields/Fields/Multienum/DetailView.tpl
  include/SugarFields/Fields/Multienum/ListView.tpl
  themes/SuiteP/include/Popups/tpls/PopupGeneric.tpl
Labels: bug, General, not urgent
