Repository SinergiaTIC/SinergiaCRM, pull requests merged in 2024-12, with the labels that each got.

#486 Enhancement - Plantillas PDF - Valores del checkbox traducidos
  modules/AOS_PDF_Templates/language/ca_ES.lang.php
  modules/AOS_PDF_Templates/language/en_us.lang.php
  modules/AOS_PDF_Templates/language/es_ES.lang.php
  modules/AOS_PDF_Templates/language/gl_ES.lang.php
  modules/AOS_PDF_Templates/templateParser.php
Labels: General, Plantillas PDF

#447 Hotfix - General - Añadir relación entre actividades y personas desde subpanel
  data/SugarBean.php
Labels: General, not urgent

#490 Hotfix - Encuestas - Evitar poder accionar el botón de envío de respuesta a encuesta repetidamente
  modules/Surveys/Entry/Survey.php
Labels: bug, Encuestas, not urgent

#514 Hotfix - Pagos agregados - Calcular correctamente los pagos agregados de Compromisos de Pago sin "Asignado a"
  modules/stic_Payments/AggregatePayments.php
  modules/stic_Payments/tpls/AggregatePayments.tpl
Labels: bug, Economía, urgent

#507 Improvement - Flujos de trabajo - Deshacer cambios y modificar índice de búsqueda
  modules/AOW_Processed/vardefs.php
  modules/AOW_WorkFlow/AOW_WorkFlow.php
Labels: Flujos de trabajo, Improvement, not urgent

#504 Hotfix - Personas y Organizaciones - Condición para aviso cuando email masivo
  include/javascript/EmailsComposeViewModal.js
  jssource/src_files/include/javascript/EmailsComposeViewModal.js
Labels: bug, not urgent, Personas y organizaciones

#505 Hotfix - KReports - Escapar valores del where (apóstrofe en concreto) para evitar errores SQL al filtrar
  modules/KReports/KReportQuery.php
Labels: bug, KReporter, not urgent

#470 Hotfix - Importación - Evitar uso de variable no definida
  custom/modules/Contacts/SticLogicHooksCode.php
  custom/modules/Contacts/SticUtils.php
  data/SugarBean.php
  modules/stic_Incorpora_Locations/Utils.php
Labels: bug, Importación, not urgent

#515 Hotfix - Mail Merge - Cuando se generan plantillas desde vista lista con TODOS los registros seleccionados, se respeta el orden de la vista
  modules/DHA_PlantillasDocumentos/MassGenerateDocument.php
Labels: bug, Mail Merge Reports, not urgent

#508 Hotfix - Formularios - Chequeo de variables vacías
  modules/stic_Web_Forms/Catcher/Include/Payment/PaymentController.php
Labels: bug, Formularios web

#511 Improvement - Validación de importación - Eliminar validación innecesaria del proceso de validación de importación
  modules/stic_Import_Validation/ImporterValidationFunctions.php
Labels: bug, Importación

#499 Enhancement - Modelo 182 - Aplicación de nueva normativa
  modules/stic_Payments/GenerateModel182.php
Labels: enhancement, Economía, M182

#493 Improvement - Actividades - En Reuniones, al hacer un KReport no aparece la relación que tiene con proyectos
  modules/Meetings/vardefs.php
Labels: Actividades, Improvement, not urgent

#472 Hotfix - General - Actualización masiva en campo multienum no trataba correctamente el valor para "limpiar" el campo
  include/MassUpdate.php
Labels: bug, General, not urgent

#488 Hotfix - Administración - Valores por defecto de DateTime traducidos y valor "first day of next month" corregido
  include/language/ca_ES.lang.php
  include/language/en_us.lang.php
  include/language/es_ES.lang.php
  include/language/gl_ES.lang.php
  modules/DynamicFields/templates/Fields/TemplateDatetimecombo.php
Labels: bug, Administración del CRM, General

#518 Hotfix - Importación - Evitar errores innecesarios en el log
  modules/Import/Importer.php
  modules/stic_Attendances/Utils.php
  modules/stic_Import_Validation/Importer.php
  modules/stic_Registrations/Utils.php
Labels: bug, Importación, not urgent

#524 Hotfix - KReports - Deshacer los cambios del PR #505
  modules/KReports/KReportQuery.php
Labels: bug, KReporter, urgent

#525 Hotfix - Personas y Organizaciones - Enlace email no funciona
  include/javascript/EmailsComposeViewModal.js
  jssource/src_files/include/javascript/EmailsComposeViewModal.js
Labels: bug, Personas y organizaciones, urgent
