Repository SinergiaTIC/SinergiaCRM, pull requests merged in 2024-11, with the labels that each got.

#384 Hotfix - Grupos de Seguridad - La importación de registros podía generar error cuando había reglas
  modules/stic_Security_Groups_Rules/Utils.php
Labels: bug, Grupos de seguridad, not urgent

#407 Hotfix - Incorpora - Sincronización desde selección masiva
  modules/stic_Incorpora/controller.php
Labels: bug, Inserción laboral, not urgent

#402 Hotfix - Notas - Añadir popupdefs.php para poder configurar la ventana emergente
  modules/Notes/metadata/popupdefs.php
Labels: bug, Notas

#385 Incidencia - Registro horario - Mostrar botón esté Ajax UI activado o desactivado
  include/javascript/ajaxUI.js
  jssource/src_files/include/javascript/ajaxUI.js
Labels: bug, not urgent, Registro horario

#423 Hotfix - Vistas Personalizadas - Verificación correcta de condiciones numéricas
  modules/stic_Custom_Views/processor/LogicHooksCode.php
  modules/stic_Custom_Views/processor/js/sticCV_Record_Field_Content.js
Labels: bug, urgent, Vistas personalizadas

#417 Hotfix - Usuarios - Generación automática de contraseña con requisitos de seguridad
  modules/Users/User.php
Labels: bug, not urgent, Usuarios y roles

#406 Hotfix - Reuniones - "Run Email Reminder Notifications" no se ejecuta al eliminar una persona
  modules/Reminders/Reminder.php
Labels: bug, Actividades, General

#429 Hotfix - Plantillas PDF - Formatear número con las preferencias del usuario
  SticInclude/Utils.php
Labels: bug, Plantillas PDF

#411 Improvement - Flujos de trabajo - Uso de índices y búsqueda corregida
  modules/AOW_WorkFlow/AOW_WorkFlow.php
Labels: bug, Flujos de trabajo, Improvement, not urgent

#412 Improvement - Personas y Organizaciones - Incluir índice por número de identificación
  SticInstall/sql/common/Indices.sql
  SticUpdates/Migrations/20240930_Indices_identification_number.sql
Labels: Formularios web, Improvement, not urgent, Personas y organizaciones

#418 Hotfix - Personas y Organizaciones - Aviso en acción masiva de envío de correo
  custom/Extension/application/Ext/Language/ca_ES.SticLang.php
  custom/Extension/application/Ext/Language/en_us.SticLang.php
  custom/Extension/application/Ext/Language/es_ES.SticLang.php
  custom/Extension/application/Ext/Language/gl_ES.SticLang.php
  include/javascript/EmailsComposeViewModal.js
  jssource/src_files/include/javascript/EmailsComposeViewModal.js
Labels: bug, not urgent, Personas y organizaciones

#448 Hotfix - Formularios - Eliminar mensajes de error innecesarios
  modules/stic_Web_Forms/Catcher/Donation/DonationBO.php
  modules/stic_Web_Forms/Catcher/Donation/DonationController.php
  modules/stic_Web_Forms/Catcher/Donation/DonationMailer.php
  modules/stic_Web_Forms/Catcher/EventInscription/EventInscriptionBO.php
  modules/stic_Web_Forms/Catcher/EventInscription/EventInscriptionController.php
  modules/stic_Web_Forms/Catcher/EventInscription/EventInscriptionMailer.php
  modules/stic_Web_Forms/Catcher/Include/Mailer/WebFormMailer.php
Labels: bug, Formularios web, not urgent

#437 Hotfix - Formularios Web - Excluir campos IFrame y WYSIWYG de los campos posibles de un formulario
  modules/stic_Web_Forms/Assistant/AssistantController.php
Labels: bug, Formularios web, not urgent

#428 Hotfix - Pagos agregados - Evitar multiplicar por 100 si el usuario no tiene separador de decimales definido
  modules/stic_Payments/AggregatePayments.php
Labels: bug, Economía, not urgent

#414 Hotfix - Pagos agregados - Errores en cálculo de pagos agregados con pagos no remesados del año anterior
  modules/stic_Payments/AggregatePayments.php
Labels: bug, Economía, urgent

#464 Hotfix - Administración - Error en la edición, clonación y cancelación de un campo HTML en Estudio
  modules/DynamicFields/templates/Fields/Forms/html.tpl
  modules/ModuleBuilder/tpls/MBModule/field.tpl
Labels: bug, Administración del CRM

#377 Hotfix - Emails - Mostrar notas adjuntas en el subpanel de Datos Adjuntos del email
  modules/Emails/Email.php
Labels: bug, Correo, Notas, not urgent

#410 Hotfix - Apariencia - Asegurar visibilidad del botón Enviar al recuperar constraseña
  themes/SuiteP/css/Stic/SticCustom.scss
  themes/SuiteP/css/Stic/style.css
  themes/SuiteP/css/SticCustom/style.css
Labels: bug, Apariencia

#405 Hotfix - General - Evitar la regeneración innecesaria de ficheros de idioma
  include/SugarObjects/LanguageManager.php
  modules/ResourceCalendar/language/ca_ES.lang.php
  modules/ResourceCalendar/language/en_us.lang.php
  modules/ResourceCalendar/language/es_ES.lang.php
  modules/ResourceCalendar/language/gl_ES.lang.php
  modules/stic_MessagesMan/Menu.php
  modules/stic_MessagesMan/vardefs.php
  modules/stic_Web_Forms/Catcher/WebFormDataBO.php
  modules/stic_Web_Forms/Catcher/WebFormDataController.php
Labels: bug, Formularios web, General, not urgent

#219 Enhancement - Traducciones - Traducciones 202405
  SticInstall/sql/ca/EmailTemplates.sql
  SticInstall/sql/es/EmailTemplates.sql
  include/language/ca_ES.lang.php
  include/language/ca_ES.notify_template.html
  include/language/es_ES.lang.php
  include/language/es_ES.notify_template.html
  modules/Administration/language/es_ES.lang.php
  modules/EmailMan/language/es_ES.lang.php
  modules/FP_Event_Locations/language/ca_ES.lang.php
  modules/KReports/language/ca_ES.lang.php
Labels: enhancement, not urgent, Traducciones

#432 Hotfix - Mail Merge - Mostrar campos en la Vista Emergente
  modules/DHA_PlantillasDocumentos/metadata/popupdefs.php
Labels: bug, Mail Merge Reports

#481 Hotfix - General - Eliminar ficheros indebidos
  modules/stic_MessagesMan/Menu.php
  modules/stic_MessagesMan/vardefs.php
Labels: bug, General, not urgent
