Repository SinergiaTIC/SinergiaCRM, pull requests merged in 2024-03, with the labels that each got.

#146 Hotfix - Settings - Correción de TPV_Test, card expiration & others
  SticInstall/sql/ca/Schedulers.sql
  SticInstall/sql/ca/Settings.sql
  SticInstall/sql/en/Schedulers.sql
  SticInstall/sql/en/Settings.sql
  SticInstall/sql/es/Schedulers.sql
  SticInstall/sql/es/Settings.sql
  SticInstall/sql/gl/Schedulers.sql
  SticInstall/sql/gl/Settings.sql
  SticUpdates/Migrations/20240226_replan_checkExpirationDates.sql
Labels: bug, Settings

#72 Enhancement - Traducciones - Incorporación de cadenas faltantes en ca_ES, es_ES y gl_ES
  include/language/ca_ES.lang.php
  include/language/es_ES.lang.php
  include/language/gl_ES.lang.php
  modules/Project/language/es_ES.lang.php
  modules/Project/language/gl_ES.lang.php
  modules/stic_Import_Validation/language/ca_ES.lang.php
Labels: enhancement, Traducciones

#157 Hotfix - Grupos de Seguridad - Importación con reglas custom
  modules/stic_Security_Groups_Rules/Utils.php
Labels: bug, Grupos de seguridad

#136 Enhancement - Home / Calendario - Hacer visibles las flechas del dashlet del calendario
  custom/modules/Calendar/tpls/header.tpl
Labels: enhancement, General

#151 Enhancements - General - Mostrar el nombre del registro en el tooltip de registros recientes y favoritos
  custom/themes/SuiteP/tpls/_headerModuleList.tpl
Labels: enhancement, General, not urgent

#150 Improvement - Remesas - Ajuste de validaciones en generación de ficheros
  modules/stic_Remittances/GenerateSEPACreditTransfers.php
  modules/stic_Remittances/GenerateSEPADirectDebits.php
  modules/stic_Remittances/language/ca_ES.lang.php
  modules/stic_Remittances/language/en_us.lang.php
  modules/stic_Remittances/language/es_ES.lang.php
  modules/stic_Remittances/language/gl_ES.lang.php
Labels: Economía, Improvement, not urgent

#163 Hotfix - Ubicaciones - Error al importar Ubicaciones
  modules/FP_Event_Locations/FP_Event_Locations_sugar.php
Labels: bug, Eventos e inscripciones, General

#164 Feature - General - Permitir personalizar las consultas de verificación de duplicados
  custom/modules/Accounts/sticAccountsDuplicateQueries.php
  custom/modules/Contacts/sticContactsDuplicateQueries.php
  custom/modules/Leads/sticLeadsDuplicateQueries.php
  modules/Accounts/AccountFormBase.php
  modules/Accounts/ShowDuplicates.php
  modules/Contacts/ContactFormBase.php
  modules/Contacts/ShowDuplicates.php
  modules/Leads/LeadFormBase.php
  modules/Leads/views/view.showduplicates.php
Labels: General, new feature, not urgent

#5 Enhancement - Economía - Mostrar información de previsión de pagos pendientes y de pagos realizados
  SticInclude/Utils.php
  SticInstall/sql/ca/KReports.sql
  SticInstall/sql/en/KReports.sql
  SticInstall/sql/es/KReports.sql
  SticInstall/sql/gl/KReports.sql
  SticUpdates/Migrations/20230802_feature_payments_prevision.sql
  SticUpdates/Migrations/ca/20240313_feature_PaymentPrevision.sql
  SticUpdates/Migrations/es/20240313_feature_PaymentPrevision.sql
  SticUpdates/Migrations/gl/20240313_feature_PaymentPrevision.sql
  modules/stic_Payment_Commitments/LogicHooksCode.php
  modules/stic_Payment_Commitments/Utils.php
  modules/stic_Payment_Commitments/controller.php
  modules/stic_Payment_Commitments/language/ca_ES.lang.php
  modules/stic_Payment_Commitments/language/en_us.lang.php
  modules/stic_Payment_Commitments/language/es_ES.lang.php
  modules/stic_Payment_Commitments/language/gl_ES.lang.php
  modules/stic_Payment_Commitments/metadata/SearchFields.php
  modules/stic_Payment_Commitments/metadata/detailviewdefs.php
  modules/stic_Payment_Commitments/metadata/editviewdefs.php
  modules/stic_Payment_Commitments/metadata/listviewdefs.php
  modules/stic_Payment_Commitments/metadata/searchdefs.php
  modules/stic_Payment_Commitments/vardefs.php
  modules/stic_Payments/Utils.php
  modules/stic_Payments/stic_Payments.php
  modules/stic_Remittances/LogicHooksCode.php
  modules/stic_Remittances/Utils.php
Labels: Economía, new feature, not urgent

#147 Enhancement - Formularios - Uso de múltiples formularios desde un entrypoint común
  modules/stic_Web_Forms/Catcher/Donation/DonationBO.php
  modules/stic_Web_Forms/Catcher/Donation/DonationController.php
  modules/stic_Web_Forms/Catcher/Donation/DonationMailer.php
  modules/stic_Web_Forms/Catcher/Donation/DonationPaymentController.php
  modules/stic_Web_Forms/Catcher/EventInscription/EventInscriptionBO.php
  modules/stic_Web_Forms/Catcher/EventInscription/EventInscriptionController.php
  modules/stic_Web_Forms/Catcher/EventInscription/EventInscriptionMailer.php
  modules/stic_Web_Forms/Catcher/Include/Payment/PaymentBO.php
  modules/stic_Web_Forms/Catcher/WebFormDataBO.php
  modules/stic_Web_Forms/Catcher/WebFormDataController.php
  modules/stic_Web_Forms/Entrypoints/Save.php
  modules/stic_Web_Forms/Entrypoints/SaveRecaptcha.php
Labels: enhancement, Formularios web

#169 Enhancement - Traducciones - Traducciones de Galego 1.2.1
  custom/Extension/application/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Administration/Ext/Language/gl_ES.SticLang.php
  modules/stic_Journal/language/gl_ES.lang.php
  modules/stic_Remittances/language/gl_ES.lang.php
  modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_ExpirationDate/language/gl_ES.lang.php
Labels: enhancement, not urgent, Traducciones

#176 Hotfix - Economía - Formato correcto de fecha al guardar desde interfaz o código
  SticInclude/Utils.php
  SticUpdates/Migrations/20230802_feature_payments_prevision.sql
  modules/stic_Payments/stic_Payments.php
Labels: bug, Economía, urgent
