Repository SinergiaTIC/SinergiaCRM, pull requests merged in 2024-02, with the labels that each got.

#79 Hotfix - General - Misma sensibilidad en minutos entre actualización masiva y la vista de Edición
  include/MassUpdate.php
Labels: bug, General, not urgent

#85 Incidencia - Emails - Evitar que se autocomplete la contraseña
  modules/EmailMan/tpls/config.tpl
  modules/OutboundEmailAccounts/OutboundEmailAccounts.php
Labels: bug, Correo, not urgent

#29 Hotfix - Mail Merge - Los documentos DOCX generados a partir de una lista de registros son incorrectos
  modules/DHA_PlantillasDocumentos/librerias/TinyButStrong/tbs_class.php
Labels: bug, Mail Merge Reports, not urgent

#76 Hotfix - Ventas - Incluir líneas de producto al Generar documento PDF desde vista lista
  modules/AOS_PDF_Templates/formLetterPdf.php
Labels: bug, Plantillas PDF, Ventas, urgent

#128 Enhancement - KReporter - Añadir campo "Segmentación"
  SticRepair.php
  custom/Extension/application/Ext/Language/ca_ES.KReporterCore.php
  custom/Extension/application/Ext/Language/en_us.KReporterCore.php
  custom/Extension/application/Ext/Language/es_ES.KReporterCore.php
  custom/Extension/application/Ext/Language/gl_ES.KReporterCore.php
  custom/Extension/modules/KReports/Ext/Vardefs/SticVardefs.php
  modules/KReports/KReport.php
  modules/KReports/js/kreportsbase3.js
  modules/KReports/language/ca_ES.lang.php
  modules/KReports/language/en_us.lang.php
  modules/KReports/language/es_ES.lang.php
  modules/KReports/language/gl_ES.lang.php
  modules/KReports/metadata/listviewdefs.php
  modules/KReports/metadata/searchdefs.php
  modules/KReports/metadata/subpanels/default.php
  modules/KReports/tpls/EditViewFooter.tpl
  modules/KReports/vardefs.php
Labels: enhancement, KReporter

#98 Enhancement - General - SticRunScripts. Poder ejecutar un solo fichero SQL o PHP
  SticRunScripts.php
Labels: enhancement, General, not urgent

#111 Enhancement - Economía - Añadir acción de validación para avisar del próximo vencimiento de tarjetas
  SticInstall/sql/ca/Schedulers.sql
  SticInstall/sql/ca/Settings.sql
  SticInstall/sql/en/Schedulers.sql
  SticInstall/sql/en/Settings.sql
  SticInstall/sql/es/Schedulers.sql
  SticInstall/sql/es/Settings.sql
  SticInstall/sql/gl/Schedulers.sql
  SticInstall/sql/gl/Settings.sql
  SticUpdates/Migrations/ca/20240209_enhancement_checkCardExpiration.sql
  SticUpdates/Migrations/es/20240209_enhancement_checkCardExpiration.sql
  SticUpdates/Migrations/gl/20240209_enhancement_checkCardExpiration.sql
  modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_ExpirationDate/FunctionDef.php
  modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_ExpirationDate/ReportExpiringCards.php
  modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_ExpirationDate/language/ca_ES.lang.php
  modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_ExpirationDate/language/en_us.lang.php
  modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_ExpirationDate/language/es_ES.lang.php
  modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_ExpirationDate/language/gl_ES.lang.php
Labels: enhancement, Economía, not urgent

#97 Hotfix - Formularios - Tratamiento de apóstrofes en el nombre de la Organización
  modules/stic_Web_Forms/Catcher/EventInscription/EventInscriptionBO.php
Labels: bug, Formularios web

#121 Hotfix - Objetivos - Arrastrar persona/familia en subpaneles de Objetivos
  modules/stic_Goals/Utils.js
Labels: bug, not urgent, Atención Directa

#93 Feature - General - Vista de "Edición rápida"
  custom/include/generic/SugarWidgets/SugarWidgetSubPanelQuickEditButton.php
  include/ListView/ListViewSubPanel.php
  include/SugarObjects/templates/basic/language/ca_ES.lang.php
  include/SugarObjects/templates/basic/language/en_us.lang.php
  include/SugarObjects/templates/basic/language/es_ES.lang.php
  include/SugarObjects/templates/basic/language/gl_ES.lang.php
  include/SugarObjects/templates/basic/metadata/subpanels/default.php
  include/SugarObjects/templates/company/language/ca_ES.lang.php
  include/SugarObjects/templates/company/language/en_us.lang.php
  include/SugarObjects/templates/company/language/es_ES.lang.php
  include/SugarObjects/templates/company/language/gl_ES.lang.php
  include/SugarObjects/templates/company/metadata/subpanels/default.php
  include/SugarObjects/templates/file/language/ca_ES.lang.php
  include/SugarObjects/templates/file/language/en_us.lang.php
  include/SugarObjects/templates/file/language/es_ES.lang.php
  include/SugarObjects/templates/file/language/gl_ES.lang.php
  include/SugarObjects/templates/file/metadata/subpanels/default.php
  include/SugarObjects/templates/issue/language/ca_ES.lang.php
  include/SugarObjects/templates/issue/language/en_us.lang.php
  include/SugarObjects/templates/issue/language/es_ES.lang.php
  include/SugarObjects/templates/issue/language/gl_ES.lang.php
  include/SugarObjects/templates/issue/metadata/subpanels/default.php
  include/SugarObjects/templates/person/language/ca_ES.lang.php
  include/SugarObjects/templates/person/language/en_us.lang.php
  include/SugarObjects/templates/person/language/es_ES.lang.php
  include/SugarObjects/templates/person/language/gl_ES.lang.php
  include/SugarObjects/templates/person/metadata/subpanels/default.php
  include/SugarObjects/templates/sale/language/ca_ES.lang.php
  include/SugarObjects/templates/sale/language/en_us.lang.php
  include/SugarObjects/templates/sale/language/es_ES.lang.php
  include/SugarObjects/templates/sale/language/gl_ES.lang.php
  include/SugarObjects/templates/sale/metadata/subpanels/default.php
  include/language/ca_ES.lang.php
  include/language/en_us.lang.php
  include/language/es_ES.lang.php
  include/language/gl_ES.lang.php
  modules/ModuleBuilder/parsers/views/DeployedSubpanelImplementation.php
Labels: General, new feature

#113 Incidencia - Flujos de trabajo - Formateo de hora en campos calculados que no usan funciones de fecha.
  modules/AOW_Actions/actions/actionComputeField.php
Labels: bug, Flujos de trabajo

#125 Enhancement - Idiomas - Traducciones al gallego
  custom/Extension/application/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Accounts/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Calendar/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Contacts/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Home/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Opportunities/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Project/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/SecurityGroups/Ext/Language/gl_ES.SticLang.php
  custom/modules/Campaigns/language/gl_ES.lang.php
  modules/Campaigns/language/gl_ES.lang.php
  modules/KReports/language/gl_ES.lang.php
  modules/ModuleBuilder/language/gl_ES.lang.php
  modules/SharedSecurityRules/language/gl_ES.lang.php
  modules/SharedSecurityRulesActions/language/gl_ES.lang.php
  modules/SharedSecurityRulesConditions/language/gl_ES.lang.php
  modules/stic_Centers/language/gl_ES.lang.php
  modules/stic_Events/language/gl_ES.lang.php
  modules/stic_Families/language/gl_ES.lang.php
  modules/stic_Goals/language/gl_ES.lang.php
  modules/stic_Grants/language/gl_ES.lang.php
  modules/stic_Prescription/language/gl_ES.lang.php
  modules/stic_Security_Groups_Rules/language/gl_ES.lang.php
Labels: enhancement, General

#124 Enhancement - Administración - Acciones de Administrador en Sidebar
  custom/Extension/modules/Administration/Ext/Language/ca_ES.SticLang.php
  custom/Extension/modules/Administration/Ext/Language/en_us.SticLang.php
  custom/Extension/modules/Administration/Ext/Language/es_ES.SticLang.php
  custom/Extension/modules/Administration/Ext/Language/gl_ES.SticLang.php
  custom/themes/SuiteP/tpls/_headerModuleList.tpl
  modules/Administration/language/en_us.lang.php
  themes/SuiteP/css/Dawn/style.css
  themes/SuiteP/css/Day/style.css
  themes/SuiteP/css/Dusk/style.css
  themes/SuiteP/css/Night/style.css
  themes/SuiteP/css/Noon/style.css
  themes/SuiteP/css/Stic/SticCustom.scss
  themes/SuiteP/css/Stic/style.css
  themes/SuiteP/css/SticCustom/style.css
  themes/SuiteP/css/suitep-base/suitepicon-glyphs.scss
  themes/SuiteP/css/suitep-base/suitepicon.eot
  themes/SuiteP/css/suitep-base/suitepicon.html
  themes/SuiteP/css/suitep-base/suitepicon.json
  themes/SuiteP/css/suitep-base/suitepicon.svg
  themes/SuiteP/css/suitep-base/suitepicon.ttf
  themes/SuiteP/css/suitep-base/suitepicon.woff
  themes/SuiteP/css/suitep-base/suitepicon.woff2
Labels: enhancement, Administración del CRM

#131 Hotfix - KReporter - Cambiar nombre lista
  custom/Extension/application/Ext/Language/ca_ES.KReporterCore.php
Labels: KReporter
