Repository SinergiaTIC/SinergiaCRM, pull requests merged in 2024-05, with the labels that each got.

#193 Enhancement - General - Permitir selección de estilo del sidebar
  SticInclude/SticCustomScss.php
  SticInstall/sql/ca/Settings.sql
  SticInstall/sql/en/Settings.sql
  SticInstall/sql/es/Settings.sql
  SticInstall/sql/gl/Settings.sql
  SticUpdates/Migrations/ca/20240412_feature_SticCustomSidebarColor.sql
  SticUpdates/Migrations/en/20240412_feature_SticCustomSidebarColor.sql
  SticUpdates/Migrations/es/20240412_feature_SticCustomSidebarColor.sql
  SticUpdates/Migrations/gl/20240412_feature_SticCustomSidebarColor.sql
  custom/themes/SuiteP/js/style.js
  custom/themes/SuiteP/themedef.php
  custom/themes/SuiteP/tpls/_headerModuleList.tpl
  modules/stic_Settings/LogicHooksCode.php
  themes/SuiteP/css/Stic/SticCustom.scss
  themes/SuiteP/css/Stic/SticPalette.scss
  themes/SuiteP/css/Stic/style.css
  themes/SuiteP/css/Stic/variables.scss
  themes/SuiteP/css/SticCustom/CustomPalette.scss
  themes/SuiteP/css/SticCustom/style.css
Labels: enhancement, Apariencia, General

#207 Improvement - SinergiaDA - Mover cadenas a los ficheros adecuados
  custom/Extension/application/Ext/Language/ca_ES.SticLang.php
  custom/Extension/application/Ext/Language/ca_ES.SticLang_SDA.php
  custom/Extension/application/Ext/Language/en_us.SticLang.php
  custom/Extension/application/Ext/Language/en_us.SticLang_SDA.php
  custom/Extension/application/Ext/Language/es_ES.SticLang.php
  custom/Extension/application/Ext/Language/es_ES.SticLang_SDA.php
  custom/Extension/application/Ext/Language/gl_ES.SticLang.php
  custom/Extension/application/Ext/Language/gl_ES.SticLang_SDA.php
  custom/Extension/modules/Administration/Ext/Language/ca_ES.SticLang.php
  custom/Extension/modules/Administration/Ext/Language/ca_ES.SticLang_SDA.php
  custom/Extension/modules/Administration/Ext/Language/en_us.SticLang.php
  custom/Extension/modules/Administration/Ext/Language/en_us.SticLang_SDA.php
  custom/Extension/modules/Administration/Ext/Language/es_ES.SticLang.php
  custom/Extension/modules/Administration/Ext/Language/es_ES.SticLang_SDA.php
  custom/Extension/modules/Administration/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Administration/Ext/Language/gl_ES.SticLang_SDA.php
  custom/Extension/modules/Users/Ext/Language/ca_ES.SticLang.php
  custom/Extension/modules/Users/Ext/Language/ca_ES.SticLang_SDA.php
  custom/Extension/modules/Users/Ext/Language/en_us.SticLang.php
  custom/Extension/modules/Users/Ext/Language/en_us.SticLang_SDA.php
  custom/Extension/modules/Users/Ext/Language/es_ES.SticLang.php
  custom/Extension/modules/Users/Ext/Language/es_ES.SticLang_SDA.php
  custom/Extension/modules/Users/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Users/Ext/Language/gl_ES.SticLang_SDA.php
  custom/Extension/modules/Users/Ext/Vardefs/SticVardefs.php
  custom/Extension/modules/Users/Ext/Vardefs/SticVardefs_SDA.php
Labels: Improvement, not urgent, SinergiaDA, Traducciones

#191 Hotfix - Formularios web - Stripe: Eliminación de métodos de pago erróneos en producción
  modules/stic_Web_Forms/Assistant/Donation/DonationController.php
Labels: bug, Formularios web, not urgent

#214 Hotfix - Vistas Personalizadas - No se verifican correctamente las condiciones negadas
  modules/stic_Custom_Views/processor/js/sticCV_Record_Field_Content.js
Labels: bug, not urgent, Vistas Personalizadas

#202 Hotfix - Ayudas - Error en las listas de tipo y subtipo
  modules/stic_Grants/metadata/searchdefs.php
Labels: bug, not urgent, Atención Directa

#204 Hotfix - Validación de importación - No crear registros relacionados al validar
  modules/stic_Import_Validation/Importer.php
Labels: bug, Validación de datos, urgent

#227 Hotfix - Apariencia - Setear valores por defecto en theme/settings si faltan
  SticInclude/SticCustomScss.php
Labels: bug, Apariencia, urgent

#246 Improvement - General - Cambiar punto y coma por coma
  SticInstall/sql/es/Settings.sql
  SticInstall/sql/gl/Settings.sql
Labels: bug, Development, General, urgent

#245 Improvement - Acciones de Github - Ignorando fingerprint en conexiones SSH
  .github/workflows/Develop_CreateInstanceOnOpenedPR.yml
  .github/workflows/Develop_DeleteInstanceOnClosedPR.yml
  .github/workflows/Develop_ReinstallInstanceOnUserAction.yml
  .github/workflows/Develop_UpdateInstanceOnPush.yml
Labels: Development, Improvement

#233 Hotfix - Vistas Personalizadas - Error en ocultación de campos en vista Detalle
  modules/stic_Custom_Views/processor/js/sticCVUtils.js
  modules/stic_Custom_Views/processor/js/sticCV_Record_Field_Content.js
Labels: bug, not urgent, Vistas personalizadas

#248 Enhancement - SinergiaDA - Acceso directo para usuarios sda_allowed
  custom/Extension/application/Ext/GlobalLinks/SticGlobalLinks.php
Labels: not urgent, SinergiaDA

#253 Improvement - General - Deshabilitar carga de UI por Ajax
  config.php
Labels: General, Improvement, not urgent

#236 Hotfix - Vistas Personalizadas - Comportamiento anómalo al indicar campo "Solo lectura" y "Visible"
  modules/stic_Custom_Views/processor/js/sticCVUtils.js
  modules/stic_Custom_Views/processor/js/sticCV_Record_Field_Content.js
Labels: bug, not urgent, Vistas personalizadas
