Repository SinergiaTIC/SinergiaCRM, pull requests merged in 2024-09, with the labels that each got.

#355 Hotfix - General - No permitr edición en campos que no son de texto deshabilitados
  SticInclude/js/Utils.js
Labels: bug, General, not urgent

#360 Hotfix - Calendario laboral - Mostrar el resumen por usuario de todos los seleccionados
  modules/stic_Work_Calendar/tpls/workCalendarAssistantSummary.tpl
Labels: bug, not urgent, Calendario laboral

#329 Hotfix - Calendario laboral - Calcular nombre en actualización masiva, API, import..
  modules/stic_Work_Calendar/stic_Work_Calendar.php
Labels: bug, not urgent, Calendario laboral

#307 Enhancement - General - Incluir version del repositorio en el readme
  README.md
Labels: enhancement, General

#309 Hotfix - Plantillas PDF - No aplicar configuración TinyMCE en vista de edición
  include/SugarFields/Fields/Wysiwyg/SugarFieldWysiwyg.php
Labels: bug, not urgent, Plantillas PDF

#324 Improvement - Formularios Web - Inclusión de nombre y apellidos del pagador en el envío a Redsys
  modules/stic_Web_Forms/Catcher/Include/Payment/PaymentController.php
Labels: enhancement, Formularios web, not urgent

#368 Enhancement - Traducciones - Traducciones de Galego 1.6.2
  custom/Extension/application/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Accounts/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Administration/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Calendar/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Employees/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Users/Ext/Language/gl_ES.SticLang.php
  modules/stic_Contacts_Relationships/language/gl_ES.lang.php
  modules/stic_Custom_View_Actions/language/gl_ES.lang.php
  modules/stic_Custom_View_Conditions/language/gl_ES.lang.php
  modules/stic_Custom_View_Customizations/language/gl_ES.lang.php
  modules/stic_Custom_Views/language/gl_ES.lang.php
  modules/stic_Events/language/gl_ES.lang.php
  modules/stic_Job_Applications/language/gl_ES.lang.php
  modules/stic_Job_Offers/language/gl_ES.lang.php
  modules/stic_Payment_Commitments/language/gl_ES.lang.php
  modules/stic_Remittances/language/gl_ES.lang.php
  modules/stic_Skills/language/gl_ES.lang.php
  modules/stic_Time_Tracker/language/gl_ES.lang.php
  modules/stic_Training/language/gl_ES.lang.php
  modules/stic_Validation_Actions/DataAnalyzer/Functions/TimeTracker_HoursWorkedInPreviousWeek/language/gl_ES.lang.php
  modules/stic_Validation_Actions/DataAnalyzer/Functions/TimeTracker_MainData/language/gl_ES.lang.php
  modules/stic_Validation_Actions/DataAnalyzer/Functions/WorkCalendar_MainData/language/gl_ES.lang.php
  modules/stic_Web_Forms/language/gl_ES.lang.php
  modules/stic_Work_Calendar/language/gl_ES.lang.php
  modules/stic_Work_Experience/language/gl_ES.lang.php
Labels: enhancement, not urgent, Traducciones

#323 Hotfix - Formularios Web - Eliminar información no necesaria en formularios generados
  modules/stic_Web_Forms/Assistant/Donation/DonationController.php
  modules/stic_Web_Forms/Assistant/EventInscription/EventInscriptionController.php
Labels: bug, Formularios web, not urgent

#338 Hotfix - General - Usar el delimitador de decimales configurado en campos FLOAT
  include/SugarFields/Fields/Float/SugarFieldFloat.php
  modules/AOS_PDF_Templates/templateParser.php
  modules/EmailTemplates/EmailTemplateParser.php
  modules/KReports/KReport.php
Labels: bug, Campañas, Importación, not urgent, Plantillas PDF

#387 Hotfix - Campañas - Cargar información relacionada a la cuenta de entrada seleccionada
  custom/modules/EmailMarketing/EditView.html
Labels: bug, Campañas, not urgent

#378 Enhacement - Registro horario - Mostrar el botón aunque el usuario no tenga permiso de acceso al módulo
  modules/stic_Time_Tracker/controller.php
Labels: enhancement, not urgent, Registro horario

#388 Hotfix - Administración - Mostrar editor enriquecido de HTML tras Clonar o Cancelar edición
  modules/DynamicFields/templates/Fields/Forms/html.tpl
Labels: bug, Administración del CRM, not urgent

#339 Enhancement - Encuestas - Mensaje agradecimiento en el idioma seleccionado
  modules/Surveys/Entry/Thanks.php
  modules/Surveys/language/ca_ES.lang.php
  modules/Surveys/language/en_us.lang.php
  modules/Surveys/language/es_ES.lang.php
  modules/Surveys/language/gl_ES.lang.php
Labels: enhancement, Encuestas

#62 Hotfix - General - Ver nombre de fichero en vista de lista de un módulo propio de tipo Archivo
  custom/include/generic/SugarWidgets/SugarWidgetSubPanelFileDownloadViewLink.php
  include/ListView/ListViewData.php
  include/SugarObjects/templates/file/metadata/listviewdefs.php
  include/SugarObjects/templates/file/metadata/subpanels/default.php
Labels: bug, Administración del CRM, not urgent

#373 Enhancement - SinergiaDA - Algunas mejoras
  SticInclude/SinergiaDA.php
  modules/stic_Accounts_Relationships/SDAVardefs.php
  modules/stic_Contacts_Relationships/SDAVardefs.php
  modules/stic_Payment_Commitments/SDAVardefs.php
Labels: bug, not urgent, SinergiaDA

#44 Feature - Subvenciones - Alerta nuevas convocatorias (Notificaciones)
  SticInstall/sql/ca/EmailTemplates.sql
  SticInstall/sql/common/FieldsMetadata.sql
  SticInstall/sql/en/EmailTemplates.sql
  SticInstall/sql/es/EmailTemplates.sql
  SticInstall/sql/gl/EmailTemplates.sql
  SticUpdates/Migrations/20240705_feature_44_alertOpportunities.sql
  SticUpdates/Migrations/ca/20240904_feature_44_alertOpportunities.sql
  SticUpdates/Migrations/en/20240904_feature_44_alertOpportunities.sql
  SticUpdates/Migrations/es/20240904_feature_44_alertOpportunities.sql
  SticUpdates/Migrations/gl/20240904_feature_44_alertOpportunities.sql
  custom/Extension/application/Ext/Language/ca_ES.SticLang.php
  custom/Extension/application/Ext/Language/en_us.SticLang.php
  custom/Extension/application/Ext/Language/es_ES.SticLang.php
  custom/Extension/application/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Campaigns/Ext/Language/ca_ES.SticLang.php
  custom/Extension/modules/Campaigns/Ext/Language/en_us.SticLang.php
  custom/Extension/modules/Campaigns/Ext/Language/es_ES.SticLang.php
  custom/Extension/modules/Campaigns/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Campaigns/Ext/LogicHooks/SticLogicHooksCall.php
  custom/Extension/modules/Campaigns/Ext/Vardefs/SticVardefs.php
  custom/Extension/modules/Opportunities/Ext/Language/ca_ES.SticLang.php
  custom/Extension/modules/Opportunities/Ext/Language/en_us.SticLang.php
  custom/Extension/modules/Opportunities/Ext/Language/es_ES.SticLang.php
  custom/Extension/modules/Opportunities/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Opportunities/Ext/Layoutdefs/SticLayoutdefs.php
  custom/Extension/modules/Opportunities/Ext/Vardefs/SticVardefs.php
  custom/include/generic/SugarWidgets/SugarWidgetSubPanelCampaignTrackDetailViewLink.php
  custom/modules/Campaigns/SticLogicHooksCode.php
  custom/modules/Campaigns/SticUtils.js
  custom/modules/Campaigns/SticUtils.php
  custom/modules/Campaigns/TrackDetailView.php
  custom/modules/Campaigns/TrackDetailView.tpl
  custom/modules/Campaigns/language/gl_ES.lang.php
  custom/modules/Campaigns/metadata/subpanels/SticForNotifications.php
  custom/modules/Campaigns/views/view.edit.php
  custom/modules/Campaigns/views/view.subpanelquickcreate.php
  custom/modules/EmailTemplates/EditView.php
  modules/Campaigns/Campaign.php
  modules/Campaigns/metadata/detailviewdefs.php
  modules/Campaigns/metadata/editviewdefs.php
  modules/Campaigns/metadata/quickcreatedefs.php
  modules/Campaigns/views/view.detail.php
  modules/EmailTemplates/EmailTemplateParser.php
  modules/Opportunities/metadata/detailviewdefs.php
  modules/Opportunities/metadata/editviewdefs.php
  modules/stic_Events/language/ca_ES.lang.php
  modules/stic_Events/language/en_us.lang.php
  modules/stic_Events/language/es_ES.lang.php
  modules/stic_Events/language/gl_ES.lang.php
  modules/stic_Events/metadata/subpaneldefs.php
Labels: new feature, not urgent, Subvenciones

#354 Enhancement - Calendario laboral - Encadenar creaciones periódicas sin volver a seleccionar usuarios
  modules/stic_Work_Calendar/Menu.php
  modules/stic_Work_Calendar/language/ca_ES.lang.php
  modules/stic_Work_Calendar/language/en_us.lang.php
  modules/stic_Work_Calendar/language/es_ES.lang.php
  modules/stic_Work_Calendar/language/gl_ES.lang.php
  modules/stic_Work_Calendar/tpls/workCalendarAssistantSummary.tpl
  modules/stic_Work_Calendar/views/view.workcalendarassistant.php
  modules/stic_Work_Calendar/views/view.workcalendarassistantsummary.php
Labels: enhancement, not urgent, Calendario laboral

#398 Improvement - Plantillas PDF - Añadir PR Id en comentario
  include/SugarFields/Fields/Wysiwyg/SugarFieldWysiwyg.php
Labels: bug, Plantillas PDF
