Repository SinergiaTIC/SinergiaCRM, pull requests merged in 2024-06, with the labels that each got.

#247 Improvement - SinergiaDA - Varios cambios
  .gitignore
  SticInclude/SinergiaDA.php
  SticInclude/SinergiaDARebuild.php
Labels: Improvement, SinergiaDA

#234 Enhancement - Vistas Personalizadas - Pequeñas mejoras de usabilidad
  custom/Extension/application/Ext/Language/ca_ES.SticLang.php
  custom/Extension/application/Ext/Language/en_us.SticLang.php
  custom/Extension/application/Ext/Language/es_ES.SticLang.php
  custom/Extension/application/Ext/Language/gl_ES.SticLang.php
  modules/stic_Custom_View_Actions/language/ca_ES.lang.php
  modules/stic_Custom_View_Actions/language/en_us.lang.php
  modules/stic_Custom_View_Actions/language/es_ES.lang.php
  modules/stic_Custom_View_Actions/language/gl_ES.lang.php
  modules/stic_Custom_View_Customizations/metadata/subpanels/default.php
  modules/stic_Custom_Views/metadata/subpaneldefs.php
  modules/stic_Custom_Views/processor/js/sticCVUtils.js
  modules/stic_Custom_Views/processor/js/sticCV_Record_Field_Container.js
  modules/stic_Custom_Views/processor/js/sticCV_Record_Field_Content.js
  modules/stic_Custom_Views/processor/js/sticCV_Record_Field_Header.js
  modules/stic_Custom_Views/processor/js/sticCustomizeView.js
  modules/stic_Custom_Views/stic_Custom_Views_ModuleView.php
Labels: enhancement, not urgent, Vistas personalizadas

#251 Hotfix - Formularios Web - Pérdida del EntryPoint si algún campo contiene doble comilla
  modules/stic_Web_Forms/Assistant/AssistantController.php
Labels: bug, Formularios web, urgent

#205 Enhancement - Competencias - Rellenar el nombre con el idioma indicado en "otros" cuando esté informado
  modules/stic_Skills/stic_Skills.php
Labels: enhancement, Inserción laboral

#260 Hotfix - General - Recuperar icono de Ofertas Laborales
  themes/SuiteP/css/Dawn/style.css
  themes/SuiteP/css/Day/style.css
  themes/SuiteP/css/Dusk/style.css
  themes/SuiteP/css/Night/style.css
  themes/SuiteP/css/Noon/style.css
  themes/SuiteP/css/Stic/style.css
  themes/SuiteP/css/SticCustom/style.css
  themes/SuiteP/css/suitep-base/suitepicon-glyphs.scss
  themes/SuiteP/css/suitep-base/suitepicon.eot
  themes/SuiteP/css/suitep-base/suitepicon.html
  themes/SuiteP/css/suitep-base/suitepicon.json
  themes/SuiteP/css/suitep-base/suitepicon.svg
  themes/SuiteP/css/suitep-base/suitepicon.ttf
  themes/SuiteP/css/suitep-base/suitepicon.woff
  themes/SuiteP/css/suitep-base/suitepicon.woff2
Labels: bug, General, urgent

#262 SinergiaCRM 1.6.0 Release
  config.php
Labels: General

#265 Hotfix - SinergiaDA - Corrección en nombre de fichero de errores de rebuild
  SticInclude/SinergiaDARebuild.php
Labels: SinergiaDA

#258 Hotfix - Validación de importación - Añadir un paréntesis
  modules/stic_Import_Validation/Importer.php
Labels: bug, not urgent, Validación de datos

#268 Hotfix - Registro horario y Calendario laboral - Incidencias post despliegue
  custom/Extension/modules/Calendar/Ext/Menus/SticMenu.php
  custom/Extension/modules/Users/Ext/Vardefs/SticVardefs.php
  custom/modules/Calendar/Calendar.php
  custom/modules/Calendar/CalendarActivity.php
  custom/modules/Employees/SticUtils.js
  custom/modules/Employees/views/view.detail.php
  custom/modules/Users/SticUtils.js
  custom/modules/Users/views/view.detail.php
  custom/modules/Users/views/view.edit.php
  modules/Calendar/CalendarActivity.php
  modules/stic_Time_Tracker/stic_Time_Tracker.php
  modules/stic_Work_Calendar/Utils.php
  modules/stic_Work_Calendar/tpls/workCalendarAssistant.tpl
Labels: bug, urgent, Registro horario, Calendario laboral

#263 Hotfix - Registro horario - Error en código javascript si el módulo está desactivado
  modules/stic_Time_Tracker/menuButton/SticTimeTrackerButtonInMainMenu.js
Labels: bug, urgent, Registro horario

#271 Hotfix - Registro horario y Calendario laboral - Evitar el uso de sugar_die() cuando no es un caso de error
  modules/stic_Time_Tracker/controller.php
  modules/stic_Work_Calendar/controller.php
Labels: bug, urgent, Registro horario, Calendario laboral

#274 Hotfix - Vistas Personalizadas - Evaluación incorrecta de Condiciones en Vista Detalle
  modules/stic_Custom_View_Conditions/stic_Custom_View_Conditions.php
  modules/stic_Custom_Views/processor/js/sticCVUtils.js
  modules/stic_Custom_Views/processor/js/sticCV_Element_Div.js
  modules/stic_Custom_Views/processor/js/sticCV_Element_Label.js
  modules/stic_Custom_Views/processor/js/sticCV_Record_Field_Content.js
  modules/stic_Custom_Views/processor/js/sticCV_View_Record_Base.js
Labels: bug, not urgent, Vistas personalizadas

#282 Hotfix - Calendario laboral - No asignar valor a repeat_count cuando llega a null
  modules/stic_Work_Calendar/Utils.php
Labels: bug, urgent, Calendario laboral
