Repository SinergiaTIC/SinergiaCRM, pull requests merged in 2024-01, with the labels that each got.

#13 Hotfix - General - Comprobar si las variables están seteadas para evitar aviso de error
  SticInclude/Views.php
  custom/modules/Accounts/SticLogicHooksCode.php
  custom/modules/Contacts/SticLogicHooksCode.php
  data/SugarBean.php
  include/entryPoint.php
  modules/stic_Incorpora_Locations/Utils.php
  modules/stic_Payment_Commitments/stic_Payment_Commitments.php
  modules/stic_Payments/stic_Payments.php
Labels: bug, General, not urgent

#18 Improvement - Acciones de Github - Adaptar Github Actions (2)
  .github/workflows/Develop_UpdateInstanceOnPush.yml
Labels: Development, Improvement

#65 Hotfix - SinergiaDA - Asegurar inclusión de todos los campos
  SticInclude/SinergiaDA.php
Labels: bug, SinergiaDA

#56 Hotfix - SinergiaDA - Permitir valores simples en multienum sin `^`
  SticInclude/SinergiaDA.php
Labels: bug, SinergiaDA

#28 Hotfix - Medicación - Búsqueda por rango añadida a los campos de tipo fecha en los filtros de los módulos Prescripción médica y Registro de Medicación
  modules/stic_Medication_Log/metadata/SearchFields.php
  modules/stic_Medication_Log/vardefs.php
  modules/stic_Prescription/metadata/SearchFields.php
  modules/stic_Prescription/vardefs.php
Labels: bug, Medicación, not urgent

#49 Hotfix - Flujos de trabajo - Error en fórmula del cálculo de mes
  modules/AOW_Actions/actions/actionComputeField.php
Labels: bug, Flujos de trabajo, General

#16 Enhancement - Eventos / Sesiones - Añadir campos de Sesión en la generación de sesiones periódicas
  SticInclude/js/Utils.js
  modules/stic_Events/Utils.php
  modules/stic_Events/language/ca_ES.lang.php
  modules/stic_Events/language/en_us.lang.php
  modules/stic_Events/language/es_ES.lang.php
  modules/stic_Events/language/gl_ES.lang.php
  modules/stic_Events/tpls/SessionWizard.tpl
  modules/stic_Events/views/view.sessionassistant.php
Labels: Eventos e inscripciones, new feature, Sesiones y asistencias

#64 Incidencia - General - Modificar el nombre del subpanel Historial
  modules/ModuleBuilder/parsers/relationships/ActivitiesRelationship.php
Labels: bug, General, not urgent

#9 Hotfix - General - Corrección del script que da de alta los schedulers en inglés
  SticInstall/sql/ca/Schedulers.sql
  SticInstall/sql/en/Schedulers.sql
  SticInstall/sql/es/Schedulers.sql
  SticInstall/sql/gl/Schedulers.sql
Labels: bug, General, not urgent

#61 Hotfix - Campañas - No eliminar emails que no debían ser excluidos de la cola de mensajes
  modules/Campaigns/QueueCampaign.php
Labels: bug, Campañas, not urgent

#27 Enhancement - Formularios web - Plantilla personalizada de email para usuario asignado
  modules/stic_Web_Forms/Catcher/Donation/DonationMailer.php
  modules/stic_Web_Forms/Catcher/EventInscription/EventInscriptionMailer.php
  modules/stic_Web_Forms/Catcher/Include/Mailer/WebFormMailer.php
Labels: enhancement, Formularios web

#57 Improvement - General - Modificaciones en ReadMe
  README.md
Labels: General, Improvement

#66 Hotfix - Grupos de Seguridad - Evitar Ajax en el módulo y renombrar fichero
  config.php
  custom/Extension/modules/SecurityGroups/Ext/Menus/Menu.php
  custom/Extension/modules/SecurityGroups/Ext/Menus/SticMenu.php
Labels: bug, Grupos de seguridad, urgent

#69 Hotfix - General - Añadir modulos stic en addAjaxBannedModules de config_override
  SticUpdates/Scripts/AddSticModulesToAjaxBanned.php
Labels: bug, General, not urgent
