Repository SinergiaTIC/SinergiaCRM, pull requests merged in 2024-04, with the labels that each got.

#145 Feature - Economía - Formularios Web - Integración pasarela CECA
  SticInstall/sql/ca/Settings.sql
  SticInstall/sql/en/Settings.sql
  SticInstall/sql/es/Settings.sql
  SticInstall/sql/gl/Settings.sql
  SticUpdates/Migrations/ca/20240228_TPVCECA_Integration.sql
  SticUpdates/Migrations/es/20240228_TPVCECA_Integration.sql
  SticUpdates/Migrations/gl/20240228_TPVCECA_Integration.sql
  custom/Extension/application/Ext/EntryPointRegistry/SticEntryPoints.php
  custom/Extension/application/Ext/Language/ca_ES.SticLang.php
  custom/Extension/application/Ext/Language/en_us.SticLang.php
  custom/Extension/application/Ext/Language/es_ES.SticLang.php
  custom/Extension/application/Ext/Language/gl_ES.SticLang.php
  modules/stic_Settings/Utils.php
  modules/stic_Web_Forms/Assistant/AssistantController.php
  modules/stic_Web_Forms/Assistant/Donation/DonationController.php
  modules/stic_Web_Forms/Assistant/Donation/javascript/ExtendedWebFormPC.js
  modules/stic_Web_Forms/Assistant/EventInscription/EventInscriptionController.php
  modules/stic_Web_Forms/Catcher/EventInscription/EventInscriptionMailer.php
  modules/stic_Web_Forms/Catcher/Include/Payment/PaymentBO.php
  modules/stic_Web_Forms/Catcher/Include/Payment/PaymentController.php
  modules/stic_Web_Forms/Catcher/Include/Payment/lib/CecaResponseCodes.php
  modules/stic_Web_Forms/Catcher/Include/Payment/tpls/CecaFirstStep.html
  modules/stic_Web_Forms/Entrypoints/TPVCecaResponse.php
  modules/stic_Web_Forms/language/ca_ES.lang.php
  modules/stic_Web_Forms/language/en_us.lang.php
  modules/stic_Web_Forms/language/es_ES.lang.php
  modules/stic_Web_Forms/language/gl_ES.lang.php
Labels: Economía, Formularios web, new feature, not urgent

#180 Hotfix - Personas - Etiqueta 'Dirección - Calle' incorrecta en la Vista Detalle
  modules/Contacts/metadata/detailviewdefs.php
Labels: bug, General, Personas y organizaciones

#174 Hotfix - Flujos de Trabajo - Error identificación formato de campos custom datetime
  modules/AOW_Actions/FormulaCalculator.php
Labels: bug, Flujos de trabajo

#184 Hotfix - Encuestas - Mostrar logo correcto en encuestas cerradas
  modules/Surveys/Entry/Survey.php
Labels: bug, Encuestas, not urgent

#167 Hotfix - Resultados de validación - Eliminar los resultados obsoletos de una acción de validación
  SticInstall/sql/ca/Schedulers.sql
  SticInstall/sql/en/Schedulers.sql
  SticInstall/sql/es/Schedulers.sql
  SticInstall/sql/gl/Schedulers.sql
  SticUpdates/Migrations/20240319_changeFunctionIDInValidationAction.sql
  modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsCommitments_reportFailedRecurringPC/FunctionDef.php
  modules/stic_Validation_Actions/DataAnalyzer/Functions/PaymentsConmitments_reportFailedRecurringPC/language/gl_ES.lang.php
Labels: bug, not urgent, Validación de datos

#185 Hotfix - SinergiaDA - Evitar errores con campos llamados "email1" y otras mejoras
  SticInclude/SinergiaDA.php
Labels: bug, SinergiaDA, urgent
