Repository SinergiaTIC/SinergiaCRM, pull requests merged in 2025-05, with the labels that each got.

#638 Improvement - Usuarios - Preparar para usar versión custom de autenticación LDAP
  modules/Users/User.php
  modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticateUser.php
Labels: Improvement, Usuarios y roles

#647 Hotfix - Usuarios - Anular ejecución de consulta mariaDB que modifica emails similares
  include/SugarEmailAddress/SugarEmailAddress.php
Labels: bug, Usuarios y roles

#632 Hotfix - Organizaciones Subvencionadas - Mostrar el módulo en "Selección de módulos y Subpaneles"
  custom/Extension/application/Ext/Include/SticModules.php
Labels: bug, Subvenciones

#634 Enhancement - Incorpora - Actualizar requerimientos de sincronización con Incorpora
  SticInstall/sql/common/FieldsMetadata.sql
  SticUpdates/Migrations/20250507_enhancement_newFieldsIncorporaAPI.sql
  custom/Extension/application/Ext/Language/ca_ES.SticLang.php
  custom/Extension/application/Ext/Language/en_us.SticLang.php
  custom/Extension/application/Ext/Language/es_ES.SticLang.php
  custom/Extension/application/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Contacts/Ext/Language/ca_ES.SticLang.php
  custom/Extension/modules/Contacts/Ext/Language/en_us.SticLang.php
  custom/Extension/modules/Contacts/Ext/Language/es_ES.SticLang.php
  custom/Extension/modules/Contacts/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Contacts/Ext/Vardefs/SticVardefs.php
  modules/Contacts/metadata/detailviewdefs.php
  modules/Contacts/metadata/editviewdefs.php
  modules/Contacts/metadata/quickcreatedefs.php
  modules/stic_Incorpora/utils/FieldsDef.php
  modules/stic_Incorpora/utils/IncorporaCredentials.php
  modules/stic_Incorpora/utils/Portlet_IncorporaWS_Beneficiario.xml
  modules/stic_Incorpora/utils/Portlet_IncorporaWS_Empresa.xml
  modules/stic_Incorpora/utils/Portlet_IncorporaWS_Oferta.xml
  modules/stic_Incorpora/utils/TransformedLists.php
Labels: enhancement, Inserción laboral
