Repository SinergiaTIC/SinergiaCRM, pull requests merged in 2025-03, with the labels that each got.

#571 Improvement - SinergiaDA - Limitación de usuarios para SDA y otras mejoras
  ModuleInstall/ModuleInstaller.php
  SticInclude/SinergiaDA.php
  SticInclude/SinergiaDARebuild.php
  custom/Extension/application/Ext/GlobalLinks/SticGlobalLinks.php
  custom/Extension/modules/Administration/Ext/Administration/SticManageSdaIntegration.php
  custom/Extension/modules/Administration/Ext/Language/ca_ES.SticLang.php
  custom/Extension/modules/Administration/Ext/Language/en_us.SticLang.php
  custom/Extension/modules/Administration/Ext/Language/es_ES.SticLang.php
  custom/Extension/modules/Administration/Ext/Language/gl_ES.SticLang.php
  modules/Administration/QuickRepairAndRebuild.php
Labels: Improvement, SinergiaDA

#600 Incidencia - General - Desactivar nueva lógica de prefencias de usuario en $_SESSION
  modules/UserPreferences/UserPreference.php
Labels: bug, General

#601 Hotfix - ModuleBuilder - No cargar etiquetas globales en los nuevos módulos
  modules/ModuleBuilder/MB/MBLanguage.php
Labels: bug, General, urgent

#606 Hotfix - Vistas Personalizadas - Procesar correctamente los valores de fecha sin horas
  modules/stic_Custom_Views/processor/LogicHooksCode.php
Labels: bug, urgent, Vistas personalizadas
