Repository SinergiaTIC/SinergiaCRM, pull requests merged in 2025-06, with the labels that each got.

#561 Improvement - General - Monitorización estado instancia
  SticMonitor.php
Labels: General, Improvement

#502 Hotfix - Administración - Altura de IFrame no se recogía al cambiarla
  modules/DynamicFields/DynamicField.php
  modules/DynamicFields/templates/Fields/TemplateIFrame.php
  modules/ModuleBuilder/parsers/StandardField.php
Labels: bug, Administración del CRM, General

#598 Incidencia - General - Eliminación de carpeta JAccount
  modules/JAccount/language/ca_ES.lang.php
  modules/JAccount/language/es_ES.lang.php
  modules/JAccount/language/gl_ES.lang.php
Labels: bug, General

#659 Hotfix - Plantillas de Email - No llamar a la funcion loadtemplate()
  custom/modules/EmailTemplates/SticSuiteEditorConnector.php
Labels: bug, Correo

#662 Hotfix - General - Error al importar usuarios
  modules/Users/User.php
Labels: bug, not urgent, Usuarios y roles

#594 Hotfix - General - Añadir clase pseudo-disabled para preservar datos en campos desactivados
  SticInclude/js/Utils.js
  themes/SuiteP/css/Stic/SticCustom.scss
  themes/SuiteP/css/Stic/style.css
  themes/SuiteP/css/SticCustom/style.css
Labels: bug, General

#533 Improvement - General - Visualización de detalles adicionales en popup emergente
  SticInclude/js/SticGetAdditionalDetails.js
Labels: General, Improvement, not urgent

#575 Enhancement - Plantillas PDF - Tipo de Descuento con % y €
  modules/AOS_PDF_Templates/templateParser.php
Labels: enhancement, General, Plantillas PDF

#565 Hotfix - Tareas de Proyectos - Visualizar las Tareas de Proyecto no completadas en el Dashlet
  include/language/es_ES.lang.php
  include/language/gl_ES.lang.php
  modules/ProjectTask/Dashlets/MyProjectTaskDashlet/MyProjectTaskDashlet.php
Labels: bug, General, Proyectos

#683 Hotfix - Sinergiada - Corrección de etiquetas de campos virtuales
  modules/stic_Contacts_Relationships/language/gl_ES.lang.php
  modules/stic_Payment_Commitments/language/ca_ES.lang.php
  modules/stic_Payment_Commitments/language/en_us.lang.php
  modules/stic_Payment_Commitments/language/gl_ES.lang.php
Labels: bug, SinergiaDA

#678 Hotfix - Flujos de Trabajo - Uso correcto de campos de tipo fecha en acciones de flujos de trabajo.
  modules/AOW_Actions/actions/actionCreateRecord.php
Labels: bug, Flujos de trabajo, urgent

#523 Hotfix - KReports - Se desplaza el quote de los valores a operadores concretos
  modules/KReports/KReportQuery.php
  modules/KReports/js/kreportsbase2.js
Labels: bug, KReporter, not urgent

#675 Improvement - SinergiaDA - Añadir agregaciones a campos virtuales
  modules/stic_Accounts_Relationships/SDAVardefs.php
  modules/stic_Contacts_Relationships/SDAVardefs.php
  modules/stic_Payment_Commitments/SDAVardefs.php
Labels: Improvement, SinergiaDA

#627 Hotfix - SinergiaDA - Autorelaciones y mapas de coordenadas
  SticInclude/SinergiaDA.php
Labels: bug, Improvement, SinergiaDA

#661 Hotfix - General - Correcciones de errores PHP
  include/InlineEditing/InlineEditing.php
  include/Popups/Popup_picker.php
  modules/AOS_PDF_Templates/PDF_Lib/mpdf.php
  modules/Import/views/view.step4.php
  modules/ModuleBuilder/parsers/parser.label.php
  modules/stic_Import_Validation/views/view.step4.php
  modules/stic_Web_Forms/Catcher/Donation/DonationController.php
  modules/stic_Web_Forms/Catcher/Donation/DonationPaymentBO.php
Labels: bug, General, not urgent

#572 Hotfix - General - Valores de tipo Moneda alineados a la derecha
  themes/SuiteP/css/Stic/SticCustom.scss
  themes/SuiteP/css/Stic/style.css
Labels: bug, General
