Repository SinergiaTIC/SinergiaCRM, pull requests merged in 2025-09, with the labels that each got.

#724 Enhancement - Campañas - Añadir las cabeceras List-Unsubscribe en los envíos de una campaña
  modules/EmailMan/EmailMan.php
Labels: Campañas

#720 Hotfix - Entorno Familiar - Comprobar objeto de relación antes de acceder al mismo
  modules/stic_Personal_Environment/LogicHooksCode.php
Labels: Atención Directa

#552 Feature - General - Autenticación OAuth con Google y Microsoft
  config.php
  custom/Extension/modules/Administration/Ext/Language/ca_ES.SticLang.php
  custom/Extension/modules/Administration/Ext/Language/en_us.SticLang.php
  custom/Extension/modules/Administration/Ext/Language/es_ES.SticLang.php
  custom/Extension/modules/Administration/Ext/Language/eu_ES.SticLang.php
  custom/Extension/modules/Administration/Ext/Language/gl_ES.SticLang.php
  custom/Extension/modules/Users/Ext/Language/ca_ES.SticLang.php
  custom/Extension/modules/Users/Ext/Language/en_us.SticLang.php
  custom/Extension/modules/Users/Ext/Language/es_ES.SticLang.php
  custom/Extension/modules/Users/Ext/Language/eu_ES.SticLang.php
  custom/Extension/modules/Users/Ext/Language/gl_ES.SticLang.php
  custom/modules/Contacts/metadata/SearchFields.php
  custom/modules/Contacts/metadata/searchdefs.php
  custom/themes/SuiteP/tpls/login.tpl
  modules/Administration/PasswordManager.php
  modules/Administration/PasswordManager.tpl
  modules/Users/Login.php
  modules/Users/authentication/OAuthAuthenticate/OAuthAuthenticate.php
  modules/Users/authentication/OAuthAuthenticate/OAuthAuthenticateUser.php
  modules/Users/authentication/OAuthAuthenticate/OAuthAuthenticateUtils.php
  modules/Users/authentication/OAuthAuthenticate/Providers/Google/GoogleAdminTemplate.tpl
  modules/Users/authentication/OAuthAuthenticate/Providers/Google/GoogleLoginTemplate.tpl
  modules/Users/authentication/OAuthAuthenticate/Providers/Google/GoogleUtils.php
  modules/Users/authentication/OAuthAuthenticate/Providers/Microsoft/MicrosoftAdminTemplate.tpl
  modules/Users/authentication/OAuthAuthenticate/Providers/Microsoft/MicrosoftLoginTemplate.tpl
  modules/Users/authentication/OAuthAuthenticate/Providers/Microsoft/MicrosoftUtils.php
  modules/Users/authentication/OAuthAuthenticate/Providers/Microsoft/msal-browser.min.js
Labels: General, new feature
