Repository SinergiaTIC/SinergiaCRM, pull requests merged in 2025-01, with the labels that each got.

#534 Improvement - Tareas programadas - Retrasar unos segundos la ejecución del cron de envio masivo de emails de campaña.
  SticCronMassEmailCampaigns.php
  custom/include/SugarQueue/SticCronJobs.php
Labels: Improvement, Tareas programadas, Team review

#531 Enhancement - General - Establecer foco automáticamente en búsqueda global
  include/javascript/sugar_3.js
  jssource/src_files/include/javascript/sugar_3.js
Labels: enhancement, General

#537 Hotfix - Calendario laboral - Operar con todos los registros al actualizar masivamente la hora de inicio y de finalización
  modules/stic_Work_Calendar/controller.php
  modules/stic_Work_Calendar/metadata/SearchFields.php
  modules/stic_Work_Calendar/stic_Work_Calendar.php
Labels: bug, Calendario laboral

#530 Hotfix - Economía - Formularios web - No redondear pagos Paypal con decimales
  modules/stic_Web_Forms/Catcher/Include/Payment/PaymentBO.php
Labels: bug, Economía, Formularios web

#543 Improvement - General - Cambiar el ENGINE con el que se crean las tablas iniciales de SinergiaCRM
  SticInstall/sql/SuitecrmBase.sql
Labels: General, Improvement, not urgent

#548 Hotfix - Vistas Personalizadas - Ocultar módulos de Vistas personalizadas en "Selección de módulos y Subpaneles"
  custom/Extension/application/Ext/Include/SticModules.php
Labels: bug, not urgent, Vistas personalizadas

#549 Hotfix - Vistas Personalizadas - Modificación de obligatoriedad en campos multienum
  modules/stic_Custom_Views/processor/js/sticCVUtils.js
  modules/stic_Custom_Views/processor/js/sticCV_Record_Field.js
Labels: bug, not urgent, Vistas personalizadas

#529 Hotfix - Proyectos - Inclusión de ficheros javascript en view.detail.php
  custom/modules/Project/views/view.detail.php
  modules/Project/metadata/detailviewdefs.php
Labels: bug, Proyectos

#478 Enhancement - SinergiaDA - October2/November/December
  SticInclude/SinergiaDA.php
  SticInclude/SinergiaDARebuild.php
Labels: documentation, Improvement, SinergiaDA
