Repository SinergiaTIC/SinergiaCRM, pull requests merged in 2025-07, with the labels that each got.

#713 Hotfix - Flujos de Trabajo - Interpretación correcta de la fecha en acciones de flujo de trabajo
  modules/AOW_Actions/actions/actionCreateRecord.php
Labels: bug, Flujos de trabajo, urgent

#705 Hotfix - Vistas Personalizadas - Error al aplicar acciones sobre campos que ya no existen en la vista
  modules/stic_Custom_Views/processor/js/sticCV_Element_Div.js
  modules/stic_Custom_Views/processor/js/sticCV_Record_Container.js
  modules/stic_Custom_Views/processor/js/sticCV_Record_Field_Content.js
  modules/stic_Custom_Views/processor/js/sticCV_View_Record_Base.js
Labels: bug, not urgent, Vistas personalizadas

#539 Hotfix - Flujos de trabajo - Corrección del manejo de zonas horarias en flujos de trabajo desde actualización masiva.
  modules/AOW_Actions/FormulaCalculator.php
Labels: bug, Flujos de trabajo

#719 Improvement - General - Ignorar carpeta TEST en git
  .gitignore
Labels: General, Improvement

#735 Hotfix - Grupos de Seguridad - Permitir valores nulos en campos no heredables de grupos de seguridad
  modules/stic_Security_Groups_Rules/Utils.php
Labels: bug, Grupos de seguridad

#645 Hotfix - General - Recuperar el tipo de relación en relaciones con nombres largos
  include/SubPanel/SubPanelDefinitions.php
Labels: bug, General, not urgent

#554 Hotfix - Calendario laboral - Validar el envío del formulario de actualización de hora de inicio y de fin
  modules/stic_Work_Calendar/language/ca_ES.lang.php
  modules/stic_Work_Calendar/language/en_us.lang.php
  modules/stic_Work_Calendar/language/es_ES.lang.php
  modules/stic_Work_Calendar/language/gl_ES.lang.php
  modules/stic_Work_Calendar/tpls/massUpdateDatesForm.tpl
  modules/stic_Work_Calendar/views/view.massupdatedatesform.php
Labels: bug, Calendario laboral

#731 Hotfix - Flujos de trabajo - Evitar espacios en blanco que pueden provocar error en acción "Modificar campos".
  modules/AOW_Actions/actions/actionCreateRecord.js
Labels: bug, Flujos de trabajo

#663 Enhancement - General - Mejoras en el sistema de Logs con Loki
  SticInclude/SticRemoteLogLogicHooksCode.php
Labels: enhancement, General

#732 Improvement - Mail Merge Reports - Eliminar ficheros STIC de custom
  custom/modules/Contacts/DHA_DocumentTemplatesCalculatedFields.php
  modules/Contacts/DHA_DocumentTemplatesCalculatedFields.php
  modules/Opportunities/DHA_DocumentTemplatesCalculatedFields.php
Labels: Improvement, Mail Merge Reports, not urgent, urgent
